services: 
  app: 
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: expense-tracker-app
    ports:
      - "3000:3000"
    networks: 
      - testnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 15

  tests: 
    image: mcr.microsoft.com/playwright:v1.52.0-jammy
    container_name: playwright-tests
    working_dir: /tests
    volumes: 
      - .:/tests
    networks:
      - testnet
    command: ["sh", "-c", "sleep 5 && npx playwright test"]
    depends_on: 
      app: 
        condition: service_healthy
    
networks:
  testnet: 
    driver: bridge
